version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: teste_intuitive
      POSTGRES_USER: intuitive
      POSTGRES_PASSWORD: senha_correta
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: