# Usa a imagem oficial do Python como base
FROM python:3.10

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependências e instala os pacotes necessários
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o código para o diretório de trabalho
COPY . .

# Define o comando de execução do contêiner
CMD ["python", "main.py"]
